// extern_c.h — Everything specific to the `extern "C"` boundary
//
// Calling C is not simply "emit a call": the declaration, the symbol it binds
// to, and the way each argument travels all follow rules that have nothing to
// do with how Sun calls Sun. Those rules live here rather than being spread
// through the general call-expression codegen:
//
//   - a C symbol is unmangled, and `as "name"` may rename it, so the Sun-side
//     name a call site resolves to is not the symbol to look up
//   - aggregates need per-target ABI classification (see abi/c_abi.h) before
//     they can cross the boundary, which can turn one Sun argument into two
//     LLVM ones, or into a `byval` / `sret` pointer
//   - arguments in a `...` tail follow C's default argument promotions
//
// The emitter owns the bookkeeping those rules need (symbol renames and the
// lowering chosen for each declaration) so a call site only has to hand over
// prepared argument values and ask for a call.

#pragma once

#include <llvm/ADT/ArrayRef.h>
#include <llvm/ADT/STLFunctionalExtras.h>
#include <llvm/IR/Function.h>
#include <llvm/IR/Module.h>
#include <llvm/IR/Value.h>

#include <map>
#include <string>
#include <vector>

#include "codegen/abi/c_abi.h"
#include "codegen/codegen.h"
#include "semantic_analysis/types.h"

class PrototypeAST;

namespace sun::cabi {

/// One Sun-level argument, already generated by the caller. `ref` parameters
/// arrive as the address; everything else as the value. Shared Sun coercions
/// (interface conversion, move semantics, numeric widening, static_ptr
/// narrowing) are the caller's job — only C-specific handling happens here.
struct PreparedArg {
  llvm::Value* value = nullptr;
  sun::TypePtr sunType;    // type of the argument expression
  sun::TypePtr paramType;  // declared parameter type; null in a `...` tail
};

class ExternCEmitter {
 public:
  ExternCEmitter(CodegenContext& ctx, llvm::Module* module)
      : ctx_(ctx), module_(module) {}

  /// Declare a C function, applying the C ABI to its signature. Idempotent:
  /// the block pre-pass declares externs up front so they can be called
  /// before their declaration appears, and function codegen reaches the same
  /// declaration again. Re-creating would give LLVM a uniqued name
  /// (`abs.1`) that no longer matches the C symbol.
  llvm::Function* declare(const PrototypeAST& proto, llvm::Type* returnType,
                          llvm::ArrayRef<llvm::Type*> paramTypes);

  /// Record that a Sun-side name resolves to `symbol`. Call sites resolve
  /// through the module-scoped mangled name, which the C symbol never
  /// matches; only the C-extern path knows a name is one of these, so it
  /// registers the mapping rather than declare() guessing.
  void mapSunName(const std::string& sunName, const std::string& symbol);

  /// Translate a resolved Sun-side name to the C symbol it was declared
  /// under, for `extern function f(...) T as "g"`. Returns the name unchanged
  /// when it is not a renamed extern.
  const std::string& symbolFor(const std::string& sunName) const;

  /// Whether calls to `func` must go through emitCall: true when its
  /// signature needed ABI rewriting, so its LLVM parameters no longer line up
  /// one-to-one with the Sun arguments.
  bool needsMarshalling(const llvm::Function* func) const;

  /// How the actual call instruction should be emitted. Supplied by the
  /// caller so this class does not need to know about try blocks or invokes.
  using CallEmitter = llvm::function_ref<llvm::Value*(
      llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>)>;

  /// Marshal `args` per the C ABI and emit the call. Returns the Sun-level
  /// result: an address for struct returns, the value otherwise.
  llvm::Value* emitCall(llvm::Function* func, llvm::ArrayRef<PreparedArg> args,
                        CallEmitter emitCallInsn);

  /// C's default argument promotions for a value in a `...` tail: float
  /// widens to double, anything narrower than int widens to int, and a
  /// static_ptr fat pointer narrows to its data pointer. Callees read these
  /// back with va_arg at the promoted width, so skipping them hands printf
  /// and friends the wrong bytes.
  llvm::Value* promoteVararg(llvm::Value* value,
                             const sun::TypePtr& sunType) const;

 private:
  /// Attach the byval/sret attributes a lowered signature requires. Without
  /// them LLVM does not know the pointers refer to aggregates passed by value.
  void applyAttributes(llvm::Function* func,
                       const abi::SignatureLowering& lowering) const;

  /// An address for `value`, spilling to a stack slot if it is a loaded
  /// struct, so its bytes can be reread in the shapes the ABI wants.
  llvm::Value* addressOf(llvm::Value* value, llvm::Type* aggregateType) const;

  llvm::AllocaInst* entryAlloca(llvm::Type* type, const char* name) const;

  /// Load one coerced register piece from the aggregate at `aggregateAddr`.
  /// Bounces through a padded slot when the piece's type overhangs the
  /// aggregate's end (AAPCS64 reads a 12-byte struct as [2 x i64]).
  llvm::Value* loadPiece(llvm::Value* aggregateAddr, llvm::Type* pieceType,
                         uint64_t offset, uint64_t aggregateSize) const;

  /// Mirror of loadPiece for writing a returned piece back over the
  /// aggregate without touching memory past its end.
  void storePiece(llvm::Value* piece, llvm::Value* aggregateAddr,
                  uint64_t offset, uint64_t aggregateSize) const;

  const abi::SignatureLowering* loweringFor(const llvm::Function* func) const;

  CodegenContext& ctx_;
  llvm::Module* module_;

  /// Sun-side extern name -> C symbol. Name resolution rewrites call sites
  /// through the Sun name, so this is where it becomes the real symbol.
  std::map<std::string, std::string> symbolNames_;

  /// C symbol -> how its signature was lowered. Call sites need the same plan
  /// the declaration was built from; recomputing it independently would risk
  /// the two disagreeing.
  std::map<std::string, abi::SignatureLowering> lowerings_;
};

}  // namespace sun::cabi
