# Writes SUN_GIT_HASH / SUN_VERSION into OUTPUT_FILE. Runs at every build so
# the hash tracks HEAD; the file is only rewritten when the content changes so
# main.cpp is not needlessly recompiled.
#
# Inputs: SOURCE_DIR, OUTPUT_FILE, and optionally SUN_VERSION (defaults to the
# top entry in debian/changelog, then "dev").

set(GIT_HASH "unknown")
find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(
        COMMAND ${GIT_EXECUTABLE} -C ${SOURCE_DIR} rev-parse --short=12 HEAD
        OUTPUT_VARIABLE hash OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE rc ERROR_QUIET)
    if(rc EQUAL 0 AND NOT hash STREQUAL "")
        set(GIT_HASH "${hash}")
        # debian/changelog is rewritten by scripts/build-deb.sh, so it must
        # not count as a local modification.
        execute_process(
            COMMAND ${GIT_EXECUTABLE} -C ${SOURCE_DIR} status --porcelain
                    --untracked-files=no -- . ":!debian/changelog"
            OUTPUT_VARIABLE dirty OUTPUT_STRIP_TRAILING_WHITESPACE
            RESULT_VARIABLE rc ERROR_QUIET)
        if(rc EQUAL 0 AND NOT dirty STREQUAL "")
            set(GIT_HASH "${GIT_HASH}-dirty")
        endif()
    endif()
endif()

if(NOT SUN_VERSION)
    set(SUN_VERSION "dev")
    if(EXISTS ${SOURCE_DIR}/debian/changelog)
        file(STRINGS ${SOURCE_DIR}/debian/changelog first_line LIMIT_COUNT 1)
        if(first_line MATCHES "\\(([^)]+)\\)")
            set(SUN_VERSION "${CMAKE_MATCH_1}")
        endif()
    endif()
endif()

set(content "// Generated by cmake/GitVersion.cmake - do not edit
#pragma once
#define SUN_VERSION \"${SUN_VERSION}\"
#define SUN_GIT_HASH \"${GIT_HASH}\"
")

set(old "")
if(EXISTS ${OUTPUT_FILE})
    file(READ ${OUTPUT_FILE} old)
endif()
if(NOT old STREQUAL content)
    file(WRITE ${OUTPUT_FILE} "${content}")
endif()
